// Code generated by rice embed-go; DO NOT EDIT.
package router

import (
	"time"

	"github.com/GeertJohan/go.rice/embedded"
)

func init() {

	// define files
	file2 := &embedded.EmbeddedFile{
		Filename:    "index.html",
		FileModTime: time.Unix(1647453997, 0),

		Content: string("<!DOCTYPE html>\r\n\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"utf-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n\r\n    <title>{{.Title}}</title>\r\n    <meta name=\"description\" content=\"A Go Serverless! Example App\">\r\n    <meta name=\"author\" content=\"elipZis.com\">\r\n</head>\r\n\r\n<body>\r\n    <h1>{{.Title}}</h1>\r\n</body>\r\n</html>"),
	}

	// define dirs
	dir1 := &embedded.EmbeddedDir{
		Filename:   "",
		DirModTime: time.Unix(1647453997, 0),
		ChildFiles: []*embedded.EmbeddedFile{
			file2, // "index.html"

		},
	}

	// link ChildDirs
	dir1.ChildDirs = []*embedded.EmbeddedDir{}

	// register embeddedBox
	embedded.RegisterEmbeddedBox(`../view`, &embedded.EmbeddedBox{
		Name: `../view`,
		Time: time.Unix(1647453997, 0),
		Dirs: map[string]*embedded.EmbeddedDir{
			"": dir1,
		},
		Files: map[string]*embedded.EmbeddedFile{
			"index.html": file2,
		},
	})
}
